[tools]
ruby = "latest"

[env]
MISE_RUBY_DEFAULT_PACKAGES_FILE = "{{ env.HOME }}/.config/ruby/default-gems"
RUBOCOP_TARGET_VERSION = "3.0"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[hooks]
postinstall = "{{ env.HOME }}/.local/share/mise/scripts/ruby-lsp.sh"
