---
plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: <%= ENV['RUBOCOP_TARGET_VERSION'] || '3.0' %>
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
